import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import LandingPage from "./LandingPage";
import Nav from "@/components/Nav";
import Contacts from "@/components/landingPage/Contacts";
import { useState } from "react";
import NoService from "./NoService";
import BeautyInTheSun from "./BeautyInTheSun";
import CollectionList from "./CollectionList";
import ItemType from "./ItemType";
import Cart from "./Cart";
import News from "./News";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Gallery from "./Gallery";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [page, setPage] = useState("LandingPage");
  return (
    <GoogleOAuthProvider clientId="403570061004-3kuhlc7naqtv8v1rjelru82klh92ooss.apps.googleusercontent.com">
      <Head>
        <title>Salfiyah Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/salfiyah-logo.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className=" overflow-x-hidden font-nunito bg-bg">
        <Nav
          noService={() => setPage("NoService")}
          hijabs={() => setPage("hijabs")}
          clothes={() => setPage("clothes")}
          pants={() => setPage("pants")}
          Cart={() => setPage("Cart")}
          News={() => setPage("News")}
          Gallery={() => setPage("Gallery")}
          navStatus={page}
        />
        {page === "LandingPage" && (
          <LandingPage
            beautyInTheSun={() => setPage("BeautyInTheSun")}
            noService={() => setPage("NoService")}
            collectionList={() => setPage("collectionList")}
          />
        )}
        {page === "NoService" && (
          <NoService backHome={() => setPage("LandingPage")} />
        )}
        {page === "BeautyInTheSun" && (
          <BeautyInTheSun noService={() => setPage("NoService")} />
        )}
        {page === "collectionList" && <CollectionList />}
        {page === "hijabs" && <ItemType pic={"hijabs"} title={"HIJABS"} />}
        {page === "clothes" && <ItemType pic={"clothes"} title={"CLOTHES"} />}
        {page === "pants" && <ItemType pic={"pants"} title={"PANTS"} />}
        {page === "Cart" && <Cart backHome={() => setPage("LandingPage")} />}
        {page === "News" && <News noService={() => setPage("NoService")} />}
        {page === "Gallery" && <Gallery />}
        {page !== "Gallery" && (
          <Contacts noService={() => setPage("NoService")} />
        )}
      </main>
    </GoogleOAuthProvider>
  );
}
