import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import LandingPage from "./LandingPage";
import Nav from "@/components/Nav";
import Contacts from "@/components/landingPage/Contacts";
import { useState } from "react";
import NoService from "./NoService";
import BeautyInTheSun from "./BeautyInTheSun";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [page, setPage] = useState("LandingPage");
  return (
    <>
      <Head>
        <title>Salfiyah Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/salfiyah-logo.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className=" overflow-x-hidden font-nunito">
        <Nav noService={() => setPage("NoService")} />
        {page === "LandingPage" && (
          <LandingPage
            beautyInTheSun={() => setPage("BeautyInTheSun")}
            noService={() => setPage("NoService")}
          />
        )}
        {page === "NoService" && (
          <NoService backHome={() => setPage("LandingPage")} />
        )}
        {page === "BeautyInTheSun" && (
          <BeautyInTheSun noService={() => setPage("NoService")} />
        )}

        <Contacts noService={() => setPage("NoService")} />
      </main>
    </>
  );
}
